name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t kubrasyeda866/devopsguard-backend:latest ./backend

      - name: Push backend image
        run: docker push kubrasyeda866/devopsguard-backend:latest

      - name: Build frontend image
        run: docker build -t kubrasyeda866/devopsguard-frontend:latest ./frontend

      - name: Push frontend image
        run: docker push kubrasyeda866/devopsguard-frontend:latest